-- BANHAO — ledger domain: ledger_entry_groups, ledger_entries
--
-- Implements docs/DATABASE_DESIGN.md § 10, locked by DEC-034
-- ("Phase 1 Financial Integrity" — no zero-sum trigger).
--
-- CON-003 is NOT repealed by DEC-034: every order's ledger still balances
-- to zero. What changed is WHERE that is enforced — in the NestJS ledger
-- service, inside the transaction, verified continuously by a scheduled
-- reconciliation process — rather than by a database constraint trigger.
-- THIS MIGRATION DELIBERATELY CONTAINS NO SUM-TO-ZERO TRIGGER. Do not add
-- one without a new Product Owner decision superseding DEC-034.
--
-- What the database DOES enforce: immutability (these tables are never
-- updated or deleted, for any role, including service_role) and
-- idempotency (group_key is unique — DEC-028's "fail loudly on duplicate").

create table public.ledger_entry_groups (
  id uuid primary key default gen_random_uuid(),
  -- Deterministic per economic event, e.g.
  -- "payment:PAY-BH000125:txn:<providerTxnId>". Generated by the
  -- application (ADR-001) — not by this schema.
  group_key text not null,
  order_id uuid references public.orders (id) on delete restrict,
  refund_id uuid references public.refunds (id) on delete restrict,
  -- settlements is deferred from this migration set (see
  -- docs/DATABASE_MIGRATION_V1_REPORT.md) — no FK yet.
  settlement_id uuid,
  kind text not null,
  correlation_id uuid,
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now(),

  -- DEC-028's idempotency guarantee AND, per DEC-034, the unit the ledger
  -- service's zero-sum assertion runs over. A duplicate economic event
  -- fails this constraint loudly rather than silently double-recording.
  constraint ledger_entry_groups_group_key_key unique (group_key)
);

comment on table public.ledger_entry_groups is
  'DEC-034: no database-level zero-sum trigger. group_key uniqueness is idempotency (DEC-028); the sum-to-zero invariant is asserted by the NestJS ledger service inside the transaction and re-verified by scheduled reconciliation (TQ-006). Immutable and append-only for every role.';
comment on column public.ledger_entry_groups.kind is
  'Free text, deliberately unconstrained here — the taxonomy of ledger event kinds is an application concern (ADR-001), not a database one.';
comment on column public.ledger_entry_groups.settlement_id is
  'Reserved — settlements is deferred from this migration set. No FK yet.';

create index ledger_entry_groups_order_idx on public.ledger_entry_groups (order_id);

create trigger ledger_entry_groups_reject_mutation
  before update or delete on public.ledger_entry_groups
  for each row execute function public.reject_mutation();

revoke all on public.ledger_entry_groups from anon, authenticated;
alter table public.ledger_entry_groups enable row level security;

create table public.ledger_entries (
  id uuid primary key default gen_random_uuid(),
  group_id uuid not null references public.ledger_entry_groups (id) on delete restrict,
  account text not null check (account in (
    'CUSTOMER_PAYMENT', 'MERCHANT_PAYABLE', 'RIDER_PAYABLE', 'PLATFORM_REVENUE',
    'REFUND_PAYABLE', 'PROMOTION_FUNDING', 'RIDER_COMPENSATION',
    'PLATFORM_WRITE_OFF', 'RIDER_CASH_HELD' -- dormant under DEC-016
  )),
  party_type text check (party_type is null or party_type in ('CUSTOMER', 'MERCHANT', 'RIDER', 'PLATFORM')),
  party_id uuid,
  -- Signed. A group's entries must sum to zero — asserted by the
  -- application (DEC-034), not by a trigger in this migration.
  amount_satang bigint not null,
  currency char(3) not null default 'THB',
  created_at timestamptz not null default now()
);

comment on table public.ledger_entries is
  'Append-only, signed amounts. No UPDATE or DELETE for any role — a correction is a reversing entry in a new group, never an edit (DEC-014, DEC-034). No database trigger asserts groups sum to zero; that is asserted in the NestJS ledger service transaction and re-verified by reconciliation.';

create index ledger_entries_group_idx on public.ledger_entries (group_id);
create index ledger_entries_party_idx on public.ledger_entries (party_type, party_id, created_at);
create index ledger_entries_account_idx on public.ledger_entries (account, created_at);

create trigger ledger_entries_reject_mutation
  before update or delete on public.ledger_entries
  for each row execute function public.reject_mutation();

revoke all on public.ledger_entries from anon, authenticated;
alter table public.ledger_entries enable row level security;
