-- BANHAO — payment domain: payments, attempts, webhook events, transactions, refunds
--
-- Implements docs/DATABASE_DESIGN.md § 9 and § 12.
--
-- Provider-neutral throughout (DEC-015): `provider` is a free-text label,
-- never a hard-coded vendor, and no Omise/2C2P/Xendit/Stripe-specific column
-- exists anywhere in this schema. `payment_method` includes CASH because
-- DEC-016 disables Cash on Delivery in Phase 1 without removing it from the
-- model — the value is present and rejected at the service boundary, not
-- absent from the database.
--
-- Idempotency (DEC-028) is implemented as database uniqueness, not
-- convention, on every table in this migration — see the unique constraints
-- and the comment above each one.

-- ---------------------------------------------------------------------------
-- payments — 1:1 with orders
-- ---------------------------------------------------------------------------

create table public.payments (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders (id) on delete restrict,
  -- BANHAO's own reference (e.g. PAY-BH000125) — generated by the
  -- application, not this schema.
  payment_reference text not null,

  state text not null default 'CREATED' check (state in (
    'CREATED', 'PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', 'EXPIRED', 'CANCELLED',
    'REFUND_PENDING', 'REFUND_PROCESSING', 'REFUNDED',
    'CASH_PENDING', 'CASH_COLLECTED' -- dormant under DEC-016, retained not removed
  )),
  method text not null check (method in ('ONLINE', 'CASH')),
  amount_satang bigint not null check (amount_satang >= 0),
  currency char(3) not null default 'THB',

  provider text,
  provider_payment_id text,
  succeeded_at timestamptz,
  failed_at timestamptz,
  failure_reason text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  -- Idempotency: two payments can never exist for one order (DEC-028).
  constraint payments_order_id_key unique (order_id),
  constraint payments_reference_key unique (payment_reference)
);

comment on table public.payments is
  'Holds the canonical PAYMENT state — kept out of orders entirely (DEC-018, CON-001). API-only: no client SELECT, no client write. amount_satang, order_id, payment_reference, method and currency are immutable after creation for every role — see payments_enforce_immutable_columns.';
comment on column public.payments.state is
  'SUCCESS and REFUNDED are reachable ONLY from a verified provider webhook (CON-002) — nothing in this schema enforces that by itself; it is a NestJS/ADR-001 responsibility.';
comment on column public.payments.provider is
  'Free-text label. No provider SDK or provider-specific column exists in this schema (DEC-015) — Q-001 remains unselected.';

-- One row per (provider, provider_payment_id): a provider cannot be told
-- two different payments share one of its identifiers.
create unique index payments_provider_payment_idx
  on public.payments (provider, provider_payment_id)
  where provider_payment_id is not null;

create trigger payments_set_updated_at
  before update on public.payments
  for each row execute function public.set_updated_at();

create or replace function public.payments_enforce_immutable_columns()
returns trigger
language plpgsql
as $$
begin
  if TG_OP = 'DELETE' then
    raise exception 'payments are permanent and cannot be deleted (docs/DATABASE_DESIGN.md § 13)'
      using errcode = '42501';
  end if;

  if new.order_id is distinct from old.order_id
     or new.payment_reference is distinct from old.payment_reference
     or new.method is distinct from old.method
     or new.amount_satang is distinct from old.amount_satang
     or new.currency is distinct from old.currency
  then
    raise exception 'payment reference, order, method, amount and currency are immutable after creation'
      using errcode = '42501';
  end if;

  return new;
end;
$$;

create trigger payments_enforce_immutable_columns
  before update or delete on public.payments
  for each row execute function public.payments_enforce_immutable_columns();

revoke all on public.payments from anon, authenticated;
alter table public.payments enable row level security;

-- ---------------------------------------------------------------------------
-- payment_attempts — one QR / one try; rows survive expiry (DEC-029)
-- ---------------------------------------------------------------------------

create table public.payment_attempts (
  id uuid primary key default gen_random_uuid(),
  payment_id uuid not null references public.payments (id) on delete restrict,
  attempt_no int not null check (attempt_no > 0),
  state text not null default 'PENDING'
    check (state in ('PENDING', 'SUCCESS', 'FAILED', 'EXPIRED', 'CANCELLED')),
  qr_payload text,
  expires_at timestamptz,
  provider_attempt_id text,
  failure_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  -- A regenerated QR is a new attempt on the SAME payment, not a new
  -- payment (DEC-028) — this is the idempotency key for attempts.
  constraint payment_attempts_payment_attempt_no_key unique (payment_id, attempt_no)
);

comment on table public.payment_attempts is
  'Attempts retain their identity after expiry — this is what makes a late payment resolvable to a specific attempt (DEC-029). Never deleted.';

create index payment_attempts_payment_idx on public.payment_attempts (payment_id, attempt_no);

create trigger payment_attempts_set_updated_at
  before update on public.payment_attempts
  for each row execute function public.set_updated_at();

create trigger payment_attempts_reject_delete
  before delete on public.payment_attempts
  for each row execute function public.reject_delete();

revoke all on public.payment_attempts from anon, authenticated;
alter table public.payment_attempts enable row level security;

-- ---------------------------------------------------------------------------
-- payment_events — webhook ingest; THE duplicate-webhook protection
-- ---------------------------------------------------------------------------
--
-- Two-phase webhook handling (ADR-008): this table records that a verified
-- event arrived, in its own transaction, BEFORE anything else is touched —
-- so a crash mid-processing cannot erase the evidence that the event came
-- in. payment_id is nullable: an event that cannot be matched to a payment
-- is still recorded, because an unmatchable event is exactly the situation
-- that needs evidence.

create table public.payment_events (
  id uuid primary key default gen_random_uuid(),
  payment_id uuid references public.payments (id) on delete set null,
  provider text not null,
  provider_event_id text not null,
  event_type text not null,
  signature_verified boolean not null,
  raw_payload jsonb not null,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  processing_error text,

  -- THE duplicate-webhook protection (DEC-028). A second delivery of the
  -- same provider event fails this constraint; the handler catches the
  -- violation, reads back the stored outcome, and returns 200 so the
  -- provider does not retry forever.
  constraint payment_events_provider_event_key unique (provider, provider_event_id)
);

comment on table public.payment_events is
  'Duplicate-webhook protection lives in the unique (provider, provider_event_id) constraint above. Raw payload and identity are immutable for every role; only processed_at/processing_error may change after insert.';

create index payment_events_unprocessed_idx
  on public.payment_events (processed_at)
  where processed_at is null;

create or replace function public.payment_events_enforce_immutable_columns()
returns trigger
language plpgsql
as $$
begin
  if TG_OP = 'DELETE' then
    raise exception 'payment_events are permanent and cannot be deleted (docs/DATABASE_DESIGN.md § 13)'
      using errcode = '42501';
  end if;

  if new.payment_id is distinct from old.payment_id
     or new.provider is distinct from old.provider
     or new.provider_event_id is distinct from old.provider_event_id
     or new.event_type is distinct from old.event_type
     or new.signature_verified is distinct from old.signature_verified
     or new.raw_payload is distinct from old.raw_payload
     or new.received_at is distinct from old.received_at
  then
    raise exception 'payment_events are append-only except processed_at/processing_error'
      using errcode = '42501';
  end if;

  return new;
end;
$$;

create trigger payment_events_enforce_immutable_columns
  before update or delete on public.payment_events
  for each row execute function public.payment_events_enforce_immutable_columns();

revoke all on public.payment_events from anon, authenticated;
alter table public.payment_events enable row level security;

-- ---------------------------------------------------------------------------
-- payment_transactions — actual money movements the provider reports
-- ---------------------------------------------------------------------------
--
-- This is where a SURPLUS payment (a second successful transaction against
-- an already-SUCCESS payment) is recorded, so real cash never silently
-- vanishes from the books — see the ledger-domain migration for how its
-- entry-group key differs from the webhook's dedup key.

create table public.payment_transactions (
  id uuid primary key default gen_random_uuid(),
  payment_id uuid not null references public.payments (id) on delete restrict,
  payment_attempt_id uuid references public.payment_attempts (id) on delete set null,
  direction text not null check (direction in ('IN', 'OUT')),
  amount_satang bigint not null check (amount_satang > 0),
  provider_transaction_id text not null,
  occurred_at timestamptz not null default now(),

  constraint payment_transactions_provider_txn_key unique (provider_transaction_id)
);

comment on table public.payment_transactions is
  'An actual money movement the provider reported. Immutable and append-only — a duplicate payment (as opposed to a duplicate webhook event) is recorded here rather than swallowed.';

create index payment_transactions_payment_idx on public.payment_transactions (payment_id);

create trigger payment_transactions_reject_mutation
  before update or delete on public.payment_transactions
  for each row execute function public.reject_mutation();

revoke all on public.payment_transactions from anon, authenticated;
alter table public.payment_transactions enable row level security;

-- ---------------------------------------------------------------------------
-- refunds — a payment-domain state, never an order state (DEC-027)
-- ---------------------------------------------------------------------------

create table public.refunds (
  id uuid primary key default gen_random_uuid(),
  payment_id uuid not null references public.payments (id) on delete restrict,
  refund_reference text not null,
  state text not null default 'REFUND_REQUESTED' check (state in (
    'REFUND_REQUESTED', 'REFUND_PENDING', 'REFUND_PROCESSING',
    'REFUNDED', 'REFUND_REJECTED', 'REFUND_FAILED'
  )),
  amount_satang bigint not null check (amount_satang > 0),
  reason text not null,
  requested_by uuid references public.profiles (id) on delete set null,
  approved_by uuid references public.profiles (id) on delete set null,
  -- Not explicitly listed among docs/DATABASE_DESIGN.md § 9's refunds
  -- columns, but required by its own stated unique constraint
  -- "(provider, provider_refund_id)". Added to make that constraint
  -- implementable — see docs/DATABASE_MIGRATION_V1_REPORT.md.
  provider text,
  provider_refund_id text,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint refunds_reference_key unique (refund_reference)
);

comment on table public.refunds is
  'DEC-027: refund lives in the payment domain. Order = CANCELLED and Payment/Refund = REFUNDED can and do coexist — no order column ever holds a refund status. amount_satang, payment_id and refund_reference are immutable after creation. Never deleted.';

create unique index refunds_provider_refund_idx
  on public.refunds (provider, provider_refund_id)
  where provider_refund_id is not null;

create index refunds_payment_idx on public.refunds (payment_id);

create trigger refunds_set_updated_at
  before update on public.refunds
  for each row execute function public.set_updated_at();

create or replace function public.refunds_enforce_immutable_columns()
returns trigger
language plpgsql
as $$
begin
  if TG_OP = 'DELETE' then
    raise exception 'refunds are permanent and cannot be deleted (docs/DATABASE_DESIGN.md § 13)'
      using errcode = '42501';
  end if;

  if new.payment_id is distinct from old.payment_id
     or new.refund_reference is distinct from old.refund_reference
     or new.amount_satang is distinct from old.amount_satang
  then
    raise exception 'refund payment, reference and amount are immutable after creation'
      using errcode = '42501';
  end if;

  return new;
end;
$$;

create trigger refunds_enforce_immutable_columns
  before update or delete on public.refunds
  for each row execute function public.refunds_enforce_immutable_columns();

revoke all on public.refunds from anon, authenticated;
alter table public.refunds enable row level security;
